version: "3.7"
services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
    volumes:
      - ${CONFIG_PATH}:/config
      - ${DOWNLOAD_PATH}:/downloads
      - ${WATCH_PATH}:/watch
    ports:
      - "${WEB_UI_PORT}:9091"
      - 51413:51413
      - 51413:51413/udp
